version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
